flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
  QuickCheck:
    old-random: false
packages:
- '.'
extra-deps:
- haddock-library-1.10.0
- jira-wiki-markup-1.4.0
- git: https://github.com/hslua/hslua
  commit: bb9572f5d8ea8d32f1b5709499e481eb45a45773
  subdirs:
    - hslua
    - hslua-classes
    - hslua-core
    - hslua-marshalling
    - hslua-module-path
    - hslua-module-system
    - hslua-module-text
    - hslua-packaging
    - lua
    - lua-arbitrary
    - tasty-hslua
    - tasty-lua
- random-1.2.0
- unicode-collation-0.1.3
- citeproc-0.4.0.1
- commonmark-0.2
- commonmark-extensions-0.2.1.2
- commonmark-pandoc-0.2.1
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-17.12
nix:
  packages: [zlib]
