flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
packages:
- '.'
extra-deps:
- hslua-1.3.0
- hslua-module-doclayout-0.2.0.1
- hslua-module-path-0.1.0
- jira-wiki-markup-1.3.3
- commonmark-0.1.1.4
- commonmark-extensions-0.2.0.4
- commonmark-pandoc-0.2.0.1
- tasty-bench-0.1
- citeproc-0.3.0.7
#- citeproc:
#  git: https://github.com/jgm/citeproc.git
#  commit: feb3b7580c6738eec3b23921f7c1739cfba611aa
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
resolver: lts-17.2
nix:
  packages: [zlib]
